# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Itens da Refeição',
                'verbose_name': 'Item Refeição',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('meal_date', models.DateField(verbose_name='Data da Refeição')),
                ('name', models.CharField(max_length=100, verbose_name='Descricao')),
                ('estimate', models.IntegerField(verbose_name='Estimativa')),
                ('start_time', models.TimeField(verbose_name='Inicio da Refeição')),
                ('end_time', models.TimeField(verbose_name='Fim da Refeição')),
                ('status', models.BooleanField(verbose_name='Ativo')),
                ('item_meal', models.ManyToManyField(related_name='meals', to='meal.ItemMeal', verbose_name='Itens')),
            ],
            options={
                'verbose_name_plural': 'Refeições',
                'verbose_name': 'Refeição',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('quantity_people', models.IntegerField(verbose_name='Qtde de Pessoas')),
                ('item_meal', models.ManyToManyField(to='meal.ItemMeal')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='meal.Meal', verbose_name='Refeição')),
            ],
            options={
                'verbose_name_plural': 'Pratos Feitos',
                'verbose_name': 'Prato Feito',
                'ordering': ['-id'],
            },
        ),
    ]
