# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmeal',
            name='expire',
            field=models.BooleanField(default=True, verbose_name='Acabou'),
        ),
        migrations.AddField(
            model_name='itemmeal',
            name='quantity',
            field=models.BooleanField(default=0, verbose_name='Qtde Pessoas'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='item_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal.ItemMeal', verbose_name='Itens'),
        ),
    ]
