# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='quantity_people',
        ),
    ]
