# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20160726_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('item_meal', models.ManyToManyField(to='meal.ItemMeal')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='meal.Meal', verbose_name='Refeição')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Pratos Feitos',
                'verbose_name': 'Prato Feito',
            },
        ),
    ]
