# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmeal',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='itemmeal',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(verbose_name='Data da Refeição'),
        ),
    ]
