# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_auto_20160726_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='item_meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='item_meal',
            field=models.ManyToManyField(related_name='meals', to='meal.ItemMeal', verbose_name='Itens'),
        ),
    ]
